### ISSUE TITLE
dotest Scripts Throw Error When No Parameter is Passed

### ISSUE THREAD

**Issue by StephanHav** [nasa-jpl/ION-DTN#34]
### Description:
When running various example dotest scripts in the ION-DTN repository, an error is thrown if no parameter is specified. This is due to a comparison between an undefined variable $1 and a string. This issue clogs the terminal with error unnecessary messages, but is generally very low impact.

Below is a screenshot of the kind of error message that is displayed in the terminal after running the dotest shell script without supplying any parameter, which is the way the Quick Start Guide instructs you to run it:
![image](https://github.com/nasa-jpl/ION-DTN/assets/70806381/1993f7d3-17d8-4330-b5e6-ed88d859d3c7)

This example is taken from the demos/bench-tcp/, however shows up in various demos/tests:
`grep -rnw '/home/xxxxx/Documents/ION-DTN/' -e 'if \[ \$1 == "windows" \]'`
![image](https://github.com/nasa-jpl/ION-DTN/assets/70806381/878ce696-0f34-4c0b-851c-a69d3420d678)

### Details:

**Commit:** I believe the issue was introduced in the following [[commit](https://github.com/nasa-jpl/ION-DTN/commit/84dba415156a1dbe95d7b84bcc9ee2bb1f38219d)] about two years ago, when the windows parameter was added to make the test scripts compatible with Windows.

### Fix:

This can easily be solved by adding some quotes around the $1 parameter, in that case when no parameter is passed while running `./dotest` an empty string will be compared to 'windows' and no error will be displayed while still keeping the intended behavior for Windows compatibility. I will submit a Pull Request shortly with the above mentioned fix.

**Comment by iondev33** [comment]
Hi Stephan, Thank you for sharing your findings and recommended fixes. These scripts will be updated in our private development repo and mirrored back to GitHub for release 4.1.3, which is scheduled in a few weeks.

For ease of tracking progress, I am closing this one since all the fixes are now in 4.1.3 integration. Please let us know if this still happens.

Closing issue.
